<a href="https://colab.research.google.com/github/Rohith-Rongali/EE5179-2023/blob/main/Tutorials/Tutorial-1/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
print(np.__version__)
import matplotlib.pylab as plt

1.26.4


# Numpy Basics:


**Exercise #1:** Creating a numpy array with particular value

**Your Task** Create a numpy array with size 2*3 with all elements as 5.

In [4]:
# YOUR CODE STARTS HERE
arr = np.ones((2,3))*5
print(arr)

[[5. 5. 5.]
 [5. 5. 5.]]


In [ ]:
# np.array([[1,1], [1,1]])
# np.ones((2,3))*5
# np.zeros
# np.random.rand(2,3) # this produce output btw 0 to 1, how to get values from -10 to 10?
# var1 = torch.rand(2,3)
# var2 = np.random.rand(2,3)
# var1
# var1.min()
# var1.max()
# var1.mean()
# var2.argmax()
# var1 + var2 = error so, do var1.numpy() +var2

**Exercise #2:** Creating a numpy array with *random* value

**Your Task** Create a numpy array with size 2*3 with all random values

In [5]:
# YOUR CODE STARTS HERE
rand_arr = np.random.rand((2*3))
print(rand_arr)

[0.17193487 0.99629581 0.69553257 0.98273517 0.73090877 0.45953489]


**Exercise #3:** Basic NumPy operatrions

**Your Task** For the random array `arr`defined above, find the `sum` of all the elements, `mean`, `maximum` and `minimum` value

In [6]:
#YOUR CODE STARTS HERE
arr_sum = np.sum(rand_arr)
arr_mean = np.mean(rand_arr)
arr_max = np.max(rand_arr)
arr_min = np.min(rand_arr)

#YOUR CODE ENDS HERE

print(f'sum: {arr_sum}\nmean: {arr_mean}\nmax: {arr_max}\nmin:{arr_min}')

sum: 4.036942082949944
mean: 0.6728236804916573
max: 0.996295811951924
min:0.1719348651443069


**Exercise #4:** `argmin` and `argmax`

**Your Task** For the random array `arr`defined below:

*   Find the position of maximum and minimum value of above array
*   Find the indices of maximum and minimum value along each of its columns.
*   Find the indices of maximum and minimum value along each of the its rows.



In [8]:
# Define an array
arr = np.array([[5,12,51,25] ,[25,29,2,27]])
print(f'Array:\n{arr}\n')
# YOUR CODE STARTS HERE
#Find the position of maximum and minimum value of above array
max_pos = np.argmax(arr)
min_pos = np.argmin(arr)

#Find the indices of maximum and minimum value along each of its columns.
max_col_ind = np.argmax(arr, axis = 0)
min_col_ind = np.argmin(arr, axis = 0)

#Find the indices of maximum and minimum value along each of the its rows.
max_row_ind = np.argmax(arr, axis = 1)
min_row_ind = np.argmin(arr, axis = 1)

print(f'position of maximum value: {max_pos}\nposition of minimum value: {min_pos}\nmaximum column indices: {max_col_ind}\
      \nminimum column indices:{min_col_ind}\nmaximum row indices :{max_row_ind}\nminimum row indices :{min_row_ind}')

#YOUR CODE ENDS HERE

Array:
[[ 5 12 51 25]
 [25 29  2 27]]

position of maximum value: 2
position of minimum value: 6
maximum column indices: [1 1 0 1]      
minimum column indices:[0 0 1 0]
maximum row indices :[2 1]
minimum row indices :[0 2]


In [ ]:
# Maximum Column Indices: [1, 1, 0, 1]

# For each column, this array indicates the index of the maximum value in that column.
# Column 0: The maximum value is 25, which is at index 1 (second row).
# Column 1: The maximum value is 29, which is at index 1 (second row).
# Column 2: The maximum value is 51, which is at index 0 (first row).
# Column 3: The maximum value is 27, which is at index 1 (second row).


# Minimum Row Indices: [0, 2]

# For each row, this array indicates the index of the minimum value in that row.
# Row 0: The minimum value is 5, which is at column index 0.
# Row 1: The minimum value is 2, which is at column index 2.

Numpy Arrays vs. Python Lists?

    Why the need for numpy arrays? Can't we just use Python lists?
    Iterating over numpy arrays is slow. Slicing is faster

Python lists may contain items of different types. This flexibility comes at a price: Python lists store pointers to memory locations. On the other hand, numpy arrays are typed, where the default type is floating point. Because of this, the system knows how much memory to allocate, and if you ask for an array of size 100, it will allocate one hundred contiguous spots in memory, where the size of each spot is based on the type. This makes access extremely fast.


If you want to know more, we will suggest that you read this from [Jake Vanderplas's Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/). You will find that book an incredible resource for learning numpy, pandas and plotting. All the lessons are available as colab notebooks so that u can try out the commands on your own.